const ActionTypes = {
  IS_HIDDEN: 'IS_CART_HIDDEN',
  IS_HIDDEN_CURRENCY: 'IS_HIDDEN_CURRENCY',
  ADD_PRODUCT_ITEM: 'ADD_PRODUCT_ITEM',
  REMOVE_PRODUCT_ITEM: 'REMOVE_PRODUCT_ITEM',
  CLEAR_PRODUCT: 'CLEAR_PRODUCT_ITEM',
  CHANGE_CURRENCY: 'CHANGE_CURRENCY',
};


export default ActionTypes;